### ISSUE TITLE
Attribute "last_backup" does not update since 5.1.2

### ISSUE THREAD

**Issue by bcutter** [thomasmauerer/hassio-addons#107]
Since updating the addon from 5.1.1 to 5.1.2 the attribute `last_backup` is not updated anymore after newer (successful) backups.

I did not monitor the other attributes (yet), the sensor state is working fine (which is why this has been discovered just now).

```
friendly_name: Samba Backup
backups_local: 7
backups_remote: 45
total_backups_succeeded: 604
total_backups_failed: 33
last_backup: 2022-08-26 02:30
```

![grafik](https://user-images.githubusercontent.com/13799156/188289227-0989e6dc-e823-4108-ac58-33896d803945.png)

Addon has been updated to v5.1.2 on 2022-08-26 22:11:14.
![grafik](https://user-images.githubusercontent.com/13799156/188289246-21c59fac-aa2d-4cf6-ada0-c44a2bd9640e.png)

**Comment by thomasmauerer** [comment]
Fixed in v5.2.0

**Comment by bcutter** [comment]
Happened again. Seeing the exact same issue for 4 days now.

Backup is running and completes just fine. But SAMBA Backup sensor value keeps untouched.

Restarted SAMBA Backup addon already several times which made no change.

HELP ⚠️

**Comment by bcutter** [comment]
> Can we reopen or shall I open a new issue on this? @thomasmauerer

❓

Bugging me multiple times a day. That attribute just shows fake information. Addon restarted multiple times, no change. How can this addon not reliably manage to update the sensor once an update finished?

Unfortunately I can't downgrade the Supervisor... will continue with some tests. Let's just reopen the issue.

---
```
Add-on version: 5.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.12.9
 Home Assistant Supervisor: 2023.04.0
```
---

Test list (❌ = no change):
❌ restart SAMBA backup addon
❌ reload Supervisor
❌ check supervisor logs
✅ check addon logs
❌ restart Supervisor
❌ restart Home Assistant (Core)

---

Please have a look at this @thomasmauerer :

```
[23-04-15 02:00:20] INFO: Backup running ...
[23-04-15 02:00:21] INFO: Creating backup "Partial Backup 2022.12.9 2023-04-15 02:00"
[23-04-15 02:30:19] INFO: Copying backup 00e55a62 (Samba_Backup_Partial_Backup_2022_12_9_2023_04_15_02_00.tar) to share
[23-04-15 02:31:17] INFO: Deleting 8e857249 (Partial Backup 2022.12.9 2023-04-12 02:01) local
date: invalid date 'umbenannt).tar A 3454935040 Sat Apr  8 06:49:24 2023'
[23-04-15 02:31:18] INFO: Deleting Samba_Backup_Partial_Backup_2022_12_9_2023_03_01_02_00.tar on share
[23-04-15 02:31:18] INFO: Deleting  on share
[23-04-15 02:31:19] WARNING: del <filename>
[23-04-15 02:31:29] INFO: Backup finished
```

Suspicious finding 1:

```
[23-04-15 02:31:17] INFO: Deleting 8e857249 (Partial Backup 2022.12.9 2023-04-12 02:01) local
date: invalid date 'umbenannt).tar A 3454935040 Sat Apr  8 06:49:24 2023'
```

Suspicious finding 2:

```
[23-04-15 02:31:19] WARNING: del <filename>
```

**Might this be related to this issue? So in the end the last backup attribute is not updated because of the "date error" ?**
