### ISSUE TITLE
Backup to remote Samba server

### ISSUE THREAD

**Issue by PedroKTFC** [thomasmauerer/hassio-addons#121]
Hope this isn't the wrong way of raising this (apologies if it is).

I have a QNAP NAS which acts as a Samba server to which I can successfully back up my local HA instance. I also have a remote HA instance and ideally I'd like to back up this remote instance over the internet to my NAS. I was thinking I could set up OpenVPN on the NAS and use that to connect between the remote HA and local NAS but I'm struggling to think through the logic. Has anyone else tried this and got it working? Maybe I'm missing something obvious.

**Comment by thomasmauerer** [comment]
This is actually a networking topic, not a Samba Backup issue. The device that runs Home Assistant must be able to connect to your NAS. You need to setup port forwarding and use a service like Duck DNS to achieve that.

Please use the forum for such questions. There are more people that can help you setting this up.

**Comment by ovizii** [comment]
This worked for me via tailscale. Until 1-2 days ago. Still investigating the issue, but I can tell you the way I had set it up: tailscale add-on on HA and tailscale on the machine providing the samba backup. Worked flawlessly.
