### ISSUE TITLE
Persistent notification on error

### ISSUE THREAD

**Issue by natbrood** [thomasmauerer/hassio-addons#123]
Hi there, I'd like to request a new feature.

Recently I discovered that the last backup was 3 months ago, I have not had to restore (or look at) any backups. The add-in has worked correctly, but due to a change on the side of the samba share itself it was no longer able to acces the share.
This resulted in months without backups and me believing that this would take care of itself.

Although I recognize that this was my own responsibility and I should have ensured things worked, I would like to propose a new feature so that I, as well as other people, won't be in this scenario again (or have less of a chance, at least).

When the add-in quits/breaks/stops on an error, please add a simple Persistent notification to the dashboard. Notifying the user/admin that the integration has been unable to run/has quit out.

Thank you so much in advance

**Comment by thomasmauerer** [comment]
Hi, the addon provides a sensor which switches to the state "FAILED" in this case --> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#home-assistant-sensor

You can use that in an automation and send you a push notification to your mobile device for instance.
