### ISSUE TITLE
exclude sub folders

### ISSUE THREAD

**Issue by shannonhochkins** [thomasmauerer/hassio-addons#125]
I've been trying to find a good backup service that works with HA/supervisor, all the backup integrations i've tried only allow you to exclude top level folders (/media, /config, /share etc) - I store all my camera assets under /config/www/cameras and i'd like to exclude this from the backup, is there a way to do this?

**Comment by thomasmauerer** [comment]
No, unfortunately that's not possible.

This addon uses (as most other backup addons) the functionality of the supervisor to create the backups. And the supervisor only allows to exclude the five folders: "config", "ssl", "share", "addons/local" and "media".
