### ISSUE TITLE
Feature Request: Write a temporary file into samba target dir while backup is running...

### ISSUE THREAD

**Issue by ronnyadam** [thomasmauerer/hassio-addons#126]
My use case is a samba share at an ubuntu server. The unbuntu server is not running 24/7, it is only up for demand, for example to access nextcloud service, recording tv shows, backuping things etc ...

Periodically the server checks if there is an job running or there is an active connection or an active device. If there is nothing to do the server goes down into suspend mode and will wake up by wol or time scheduler.

For this I would need a flag (or something else) at the ubuntu server to realise that HA samaba backup job is still active.

my suggestion / wish:
 - at samba backup start, create a file into the samba target named ".HA-backup-running" or "samba-backup-running"
 - when backup is finished, delete this file
 - I could easy enhance the 'checkshutdown' script at server side with checking the exist of this temporary file

best regards
Ronny

**Comment by thomasmauerer** [comment]
I understand your use case, but the suggestion to write a temporary file does not really convince me as this is quite a special use case and not relevant to the majority of users.

I would suggest to take a look at the `smbstatus` command --> https://www.samba.org/samba/docs/current/man-html/smbstatus.1.html
With this command you can detect active Samba connections which is the case as long as Samba Backup is copying the backup file. You could for example use that information in your script to prevent your server from suspending.

**Comment by ronnyadam** [comment]
I use the `smbstatus` command, but the connection is only active while copying the Backup Zip file to the share.

I trigger the Samba Backup if the Samba Share (my server) is available via an HA automation. The backup starts and need more than 20 minutes, in this time my Server can not check if the Backup is running or not. In this time it is possible the server suspend. The check via `smbstatus` only works in the end of the backup process...

Can you establish the Samba connection from the beginning of the Backup process and terminate after copying is done?

**Comment by ronnyadam** [comment]
My workaround is to use longer guard times before enter suspend mode on server side and use an automation to wake up for Backup Job at night.

I have to check smbstatus behavior, all other client using samba appear correctly at the smbstatus...
