### ISSUE TITLE
Fresh installation only partial backups are created

### ISSUE THREAD

**Issue by mietzen** [thomasmauerer/hassio-addons#127]
Before I installed Samba Backup, I created a local full Backup, after installation Samba Backup now only creates partial Backups (based on the local full backup?) 

It would be expected that Samba Backup would start with a new full backup, when the remote folder is empty.

In general it would be nice to have the option to always perform a full backup

**Comment by thomasmauerer** [comment]
It depends on your config. If you exclude any folders or addons, a partial backup will be created, otherwise a full backup.

See here --> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#option-exclude_addons

**Comment by mietzen** [comment]
Ah that makes sens! I was confusing partial with incremental 😖  thanks for clarification 👍
