### ISSUE TITLE
Unable to exclude add-ons

### ISSUE THREAD

**Issue by bboudewijns** [thomasmauerer/hassio-addons#129]
Hi there! First of all, thanks for a great add-on.

I am having some issues with the exclusion of some add-ons. When I navigate to the add-on configuration options, there is only a (empty) drop down list for add-ons to exclude. When I enter the add-on manually I cannot save the configuration.

Maybe this happened with a recent release of HA?

Thanks in advance!

**Comment by thomasmauerer** [comment]
Yes you are right. I see this behavior also on other addons which use lists in their configuration. Must have been caused by an update.

As a workaround for now you can switch to yaml mode and enter the addons to exclude manually under `exclude_addons`.

**Comment by bboudewijns** [comment]
Ah great. Thanks. I overlooked the yaml option

**Comment by thomasmauerer** [comment]
I don't know which exact version fixed this issue, but it works again directly on the UI without using yaml mode.
