### ISSUE TITLE
sensor.samba_backup missing and blueprint not bringing it back

### ISSUE THREAD

**Issue by BNWEIN** [thomasmauerer/hassio-addons#130]
Since updating HA the blueprint to restore the sensor.samba_backup sensor is not working

No errors or anything mentioned in log file.

**Comment by StephB67** [comment]
Hi, I have the same problem. 
HA Core 2023.1.4 / HA OS 9.4 / HA Supervisor 2022.12.1.

**Comment by BNWEIN** [comment]
My issue was the add-on was not started. After starting the add-on manually the automation ran fine.

**Comment by egaryw2011** [comment]
> Ok that explains it. There is already an issue that the addon does sometimes not start even though the option "start on boot" is active -> #116
> 
> But actually that's not a Samba Backup issue as starting addons in general is done by the supervisor.

Yes I have experienced this a couple of times, is there a work around?

**Comment by Dark-Noir** [comment]
> Ok that explains it. There is already an issue that the addon does sometimes not start even though the option "start on boot" is active -> #116
> 
> But actually that's not a Samba Backup issue as starting addons in general is done by the supervisor.

Have the same issue, but only with this addon, all my others work fine

**Comment by egaryw2011** [comment]
> 

Yep thats right, it only happens on this add on for me as well.

**Comment by godfreym29** [comment]
I'm seeing the same issue.
I am having to manually start the add-on after each reboot, even though the add-on is set to start on boot in the configuration.

**Comment by thomasmauerer** [comment]
I cannot tell why you're only seeing that issue with this addon. I noticed that problem myself one time, but never again. Anyway, I'm closing this and leave #116 open for now. Even though I don't see anything I could fix at addon level.
