### ISSUE TITLE
Make backup with Password

### ISSUE THREAD

**Issue by titou4307** [thomasmauerer/hassio-addons#131]
Hello

I use this addon since one month to backup 
It make the job perfectly

I would like to protect my backup with a password so it needeed tu put the option here : 

`Option: backup_password`

But may be I have not understanding the backup with password ....

With no password my backup come like : BACKUP.TAR in the good folder (Nas)
So if I untar this archive I could access to all the files into this....and see all the files (with other passwords) in plain text (not cool if my Nas is stolen...for example...)

If I put a password and if I have all understood, so it impossible to untar the archive without password.... And so see the file in plain text....
But with the option, the archive file can be open....

What I do not like it must done ??

Best regard

**Comment by thomasmauerer** [comment]
If you use the `backup_password` option, the content of the backup will be password-protected.
You can then only extract the .tar file itself, but you cannot extract the .tar.gz files inside, which contain the sensitive data.

**Comment by titou4307** [comment]
Hi
Many thanks for your response
I have have not understand like the process of the password function.
Now  it is OK

So I would like to verify if the archive password protected may be decompressed....

So I would like to untar the backup and after untar the file tar.gz.... with the password
You could say how I can process ?

I'am on windows and under command line there is the possibility of TAR
So I type 

`Tar xvf archive.tar `

After this I have all the file in tar.gz 
But with the password I don't know how to type this PWD for untar...

**Comment by thomasmauerer** [comment]
tar does not have a password option. The files are encrypted with AES, but this is all handled in the supervisor. I don't think there is an easy way to manually decrypt the files.

**Comment by titou4307** [comment]
Hello @thomasmauerer 

For secure a little more the HA, I would like to use Secret for the username and password

So it may be :

username : !secret usernamexxxxx
password : !secret passwordxxxxx

But it not can be registered......

Is it possible to use !secret like other password ??

**Comment by thomasmauerer** [comment]
Using credentials from the secret file is supported. Check that quotation marks are correct (I would suggest to switch to yaml mode) and make sure that the username/password exists in the secret file. It should look like this:
```
username: '!secret your_user'
password: '!secret your_pass'
```
