### ISSUE TITLE
Backup in the Online Storage Box (Hetzner)

### ISSUE THREAD

**Issue by bwwork** [thomasmauerer/hassio-addons#132]
Hello,

I can't manage to connect to my Hetzner online storage - I've already tried many things: I always get the error message:

[23-01-23 17:11:21] WARNING: do_connect: Connection to u348XXX.your-storagebox.de failed (Error NT_STATUS_IO_TIMEOUT)
[23-01-23 17:11:21] FATAL: Cannot access share. Unknown reason.

Here you can get the information about the Storage Box: https://docs.hetzner.com/de/robot/storage-box/access/access-samba-cifs

My settings:
----------------
host: u348XXX.your-storagebox.de
share: backup
target_dir: ""
username: u348XXX
password: XXXXXXXXX
keep_local: 10
keep_remote: 10
trigger_time: "05:00"
trigger_days:
  - Mon
  - Tue
  - Wed
  - Thu
  - Fri
  - Sat
  - Sun
exclude_addons: []
exclude_folders: []
backup_name: "{type} Snapshot (Samba_Backup) {date} v{version}"
----------------

What am I doing wrong? What is the solution?

Thanks a lot

**Comment by MatthiasLohr** [comment]
Same problem here.

@bwwork settings seem ok so far. The only think I'm wondering is: Documentation says for `target_dir` "if not specified"... so it sounds for me to be optional, but configuration dialog requires to put in a value. Anyway, regardless of that, I'm getting the same error.

@thomasmauerer, any idea? Can we help debugging this?

**Comment by thomasmauerer** [comment]
Regarding target_dir, I agree there is room for improvement. At the moment it is a required parameter in the schema, however you can just leave it empty: `target_dir: ""`

I cannot guarantee that this addon will work at all with an online service like Hetzner. In general there are better protocols than smb for the internet, e.g. WebDAV.

Did you disable the NetBIOS filter in your router as mentioned in the Hetzner docs?

**Comment by MatthiasLohr** [comment]
> Did you disable the NetBIOS filter in your router as mentioned in the Hetzner docs?

Yep, now :smile: 

Works! Sorry for bothering here. Anyway, since NT_STATUS_IO_TIMEOUT is mentioned in multiple issues here, maybe it could be an idea to add this information to the documentation? Basically this is not only valid for Hetzner I guess, but for all remote SMB servers.

And yes, I agree, there are better protocols - but your plugin supports SMB and I like the functionality ;)

**Comment by thomasmauerer** [comment]
Cool, happy to hear that it works now.

As far as I know NT_STATUS_IO_TIMEOUT can have multiple root causes, so it's hard to give a general suggestion. But yes it would make sense to mention the NetBIOS filter in the docs. I'll add an FAQ section.

**Comment by MatthiasLohr** [comment]
Great, thanks!

**Comment by thomasmauerer** [comment]
I thought about the target_dir parameter once more. Actually I don't want to make that an optional parameter as I think it's being used by the majority of users and optional parameters are hidden by default in the configuration UI.

I updated the docs that the target directory can be empty.
