### ISSUE TITLE
Is there some timeout causing backups lasting 3h to fail copy to SMB?

### ISSUE THREAD

**Issue by guciopl** [thomasmauerer/hassio-addons#137]
I just noticed my backups are missing on SMB share for few days. I checked log and I am getting `parse error: Invalid numeric literal at line 1, column 5` exactly after 3 hours since backup was started. Previous successful uploaded backups were completed in 2:40h, 2:44h, 2:45h, 2:50h etc.

I have now few local backup which lasted for long than 3h and all of them were not copied over SMB. Looks like timeout to me.

More people seems to have it:
https://community.home-assistant.io/t/samba-backup-create-and-store-backups-on-a-samba-share/199471/537

**Comment by thomasmauerer** [comment]
Yes, there is a timeout of 3 hours. Please take a look at #65. The solution to this problem is #79 but it's not implemented yet.

**Comment by thomasmauerer** [comment]
Since this is only a question and the issue itself is already tracked in #65, I'm closing this.
