### ISSUE TITLE
Server requested LANMAN password (share-level security) but 'client lanman auth = no' or 'client ntlmv2 auth = yes'

### ISSUE THREAD

**Issue by tkdrob** [thomasmauerer/hassio-addons#143]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Samba Backup
 Create backups and store them on a Samba share
-----------------------------------------------------------
 Add-on version: 5.2.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.4.4
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23-04-16 07:40:53] INFO: ---------------------------------------------------
[23-04-16 07:40:53] INFO: Host/Share: 10.0.1.3/Volume_2
[23-04-16 07:40:53] INFO: Target directory: hassio_backups
[23-04-16 07:40:53] INFO: Keep local/remote: all/all
[23-04-16 07:40:53] INFO: Trigger time: 00:00
[23-04-16 07:40:53] INFO: Trigger days: Sun
[23-04-16 07:40:53] INFO: ---------------------------------------------------
[23-04-16 07:40:54] WARNING: Server requested LANMAN password (share-level security) but 'client lanman auth = no' or 'client ntlmv2 auth = yes'
tree connect failed: NT_STATUS_ACCESS_DENIED
[23-04-16 07:40:54] FATAL: Cannot access share. Access denied. Please check your share permissions.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

I am attempting to connect to a DLink NAS that only supports SMB 1.0. Compatibility mode is enabled but I am still unable to connect. When exploring other options, I will try to make a change in the container.

host: 10.0.1.3
share: Volume_2
target_dir: hassio_backups
username: REDACTED
password: REDACTED
keep_local: all
keep_remote: all
trigger_time: "00:00"
trigger_days:
  - Sun
exclude_addons: []
exclude_folders: []
compatibility_mode: true

**Comment by tkdrob** [comment]
This may also be a limitation of the NAS. I assume the setting would have to be changed there but may not be possible.

**Comment by tkdrob** [comment]
This is indeed an issue with the NAS I have. It is an old DNS-323 I want to use as an offsite backup for disaster recovery. The workaround here is to update it to Alt-F firmware which not only provides samba 2.0 support but GPT a well. Perhaps there should still be more compatibility options for Samba 1.0.

**Comment by thomasmauerer** [comment]
This falls into the same category as the error that the server does not support extended security as mentioned in the FAQ --> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#why-do-i-get-this-error-at-startup-server-does-not-support-extended_security

This is a problem with the supported authentication mechanisms of your NAS. Unfortunantely, LANMAN is old and outdated.

**Comment by tkdrob** [comment]
Got it, thanks. It is actually working now with Alt-F. Samba 2.0 support was the fix.
