### ISSUE TITLE
level=error msg="Unexpected server response" parse error: Invalid numeric literal at line 1, column 11

### ISSUE THREAD

**Issue by palbent** [thomasmauerer/hassio-addons#144]
Hi,
Not sure if this is similar to #65. In my case I can't see the backup created in the homeassistant snapshot menu.

![imagem](https://user-images.githubusercontent.com/78213151/232729981-5ad1efd4-6b45-47b8-a228-db763aca223c.png)

When I ran this it took just few minutes to return an error.

![imagem](https://user-images.githubusercontent.com/78213151/232729277-f00f43c1-e4a8-4b1f-b830-6bc1b269f3b1.png)

I am running HA into a virtual machine.

Thanks

**Comment by palbent** [comment]
Thanks Thomas, you are completely right and it fixed the issue. The strange thing is I was unable to see any update available or even manually update the add-on... I fix-it by removing and reinstall it again....

Thanks again!

**Comment by thomasmauerer** [comment]
Maybe you lost the custom repository on your system. This was once reported in the forum. I have no idea why this happens. But anyway, happy to hear that the issue is resolved.
