### ISSUE TITLE
External Drive Path

### ISSUE THREAD

**Issue by nicocoetzee** [thomasmauerer/hassio-addons#145]
Hello - 

Thank you for an awesome addon! I've done a lot of clicking online but I need help figuring this out. What is the "Target Directory" path if using an external drive on a mac?

I have tried, but without any success:

/Volume/Drive/Folder
Volume/Drive/Folder
/Drive/Folder
Drive/Folder

And a combination of many others. I would really appreciate if you can help me?

Many thanks,
n.

**Comment by thomasmauerer** [comment]
The target directory is not a path to your external drive. It's only needed if you have subfolders inside a single share. Most likely you can leave it empty. What does the startup log output say when you leave it empty?

**Comment by nicocoetzee** [comment]
Thanks for the reply. If I leave it empty, it seems fine. Here is the log:

'
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Samba Backup
 Create backups and store them on a Samba share
-----------------------------------------------------------
 Add-on version: 5.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.5
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23-04-21 08:33:17] INFO: ---------------------------------------------------
[23-04-21 08:33:17] INFO: Host/Share: 192.168.1.187/nicocoetzee
[23-04-21 08:33:17] INFO: Target directory: 
[23-04-21 08:33:17] INFO: Keep local/remote: 10/50
[23-04-21 08:33:17] INFO: Trigger time: 00:00
[23-04-21 08:33:17] INFO: Trigger days: Mon Tue Wed Thu Fri Sat Sun
[23-04-21 08:33:17] INFO: ---------------------------------------------------
[23-04-21 08:33:18] INFO: Samba Backup started successfully
'

But when I add the destination folder, I get the below error.

![Screenshot 2023-04-21 at 08 35 42](https://user-images.githubusercontent.com/21128291/233677206-f4eb77b7-2d1f-49c1-9c0e-cc3e5f18835f.png)

![Screenshot 2023-04-21 at 08 37 10](https://user-images.githubusercontent.com/21128291/233677512-67966614-5b5d-44a9-b682-850ce6bf8032.png)

'
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Samba Backup
 Create backups and store them on a Samba share
-----------------------------------------------------------
 Add-on version: 5.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.5
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23-04-21 08:36:59] INFO: ---------------------------------------------------
[23-04-21 08:36:59] INFO: Host/Share: 192.168.1.187/nicocoetzee
[23-04-21 08:36:59] INFO: Target directory: Samba_BA
[23-04-21 08:36:59] INFO: Keep local/remote: 10/50
[23-04-21 08:36:59] INFO: Trigger time: 00:00
[23-04-21 08:36:59] INFO: Trigger days: Mon Tue Wed Thu Fri Sat Sun
[23-04-21 08:36:59] INFO: ---------------------------------------------------
[23-04-21 08:36:59] WARNING: cd \Samba_BA\: NT_STATUS_OBJECT_NAME_NOT_FOUND
[23-04-21 08:36:59] FATAL: Target directory does not exist. Please check your config.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
'

**Comment by nicocoetzee** [comment]
Hi - if I leave it empty, it makes the backup to my local disk vs. the
desired external drive.

**Comment by thomasmauerer** [comment]
That explains that the target directory is not a sub folder of the share "nicocoetzee", since your share points to a completely different location.

I suggest to configure a second SMB share (similar as "nicocoetzee") with a new name and the full path to your Samba_BA folder. Then you can leave target_dir empty.

**Comment by nicocoetzee** [comment]
Many thanks Thomas!
