### ISSUE TITLE
Attribute "last_backup" does not update / backup status FAILED even they are actually SUCCESSFUL

### ISSUE THREAD

**Issue by bcutter** [thomasmauerer/hassio-addons#146]
Following the closed issue #107 which does not seem to get any attention (closed).

Latest relevant information including an interesting finding:
- https://github.com/thomasmauerer/hassio-addons/issues/107#issuecomment-1505086586
- https://github.com/thomasmauerer/hassio-addons/issues/107#issuecomment-1509732100 <-- see "Suspicious finding 1" + "Suspicious finding 2" ⚠

**Comment by bcutter** [comment]
Ping @thomasmauerer

**Comment by bcutter** [comment]
Ping2 @thomasmauerer are you able to have a look at this please?

![grafik](https://github.com/thomasmauerer/hassio-addons/assets/13799156/512e6a9d-1675-40d5-a70f-c59eac1c7d96)

It runs daily and completely reliable, it's just the "Last backup" attribute (which is important as I'm using it for automation purposes, getting multiple reminders a day for 5 weeks now!):

![grafik](https://github.com/thomasmauerer/hassio-addons/assets/13799156/2713bdc2-a9c7-4889-bae7-6036caaee6c7)

**I also updated my test list @ https://github.com/thomasmauerer/hassio-addons/issues/107#issuecomment-1509732100.**

**Comment by bcutter** [comment]
Ping 3 @thomasmauerer 

```
[23-06-05 02:35:05] INFO: Deleting a170f58b (Partial Backup 2022.12.9 2023-06-03 02:00) local
date: invalid date 'umbenannt).tar A 3454935040 Sat Apr  8 06:49:24 2023'
[23-06-05 02:35:06] INFO: Deleting Samba_Backup_Partial_Backup_2022_12_9_2023_04_27_02_00.tar on share
```

Seeing this on EVERY FREAKING backup run...

**Comment by bcutter** [comment]
Today I discovered this:

![image](https://github.com/thomasmauerer/hassio-addons/assets/13799156/4d8f6403-80b0-4561-b981-a113d8574ac2)

![image](https://github.com/thomasmauerer/hassio-addons/assets/13799156/95eb3851-19ab-49b3-8aa6-3d706aa326ef)

Seems like they fail for a very long time already - very likely the last "successful" run really was on April 9th.

BUT that's complete BS, as the backups are actually created fine! See here:

![image](https://github.com/thomasmauerer/hassio-addons/assets/13799156/b4a3f577-97bf-4e55-8099-40968592f963)

Might be related to #152.

Every time doing a deeper dive into SAMBA backup it looks more broken 😞 

Can we PLEASE finally have a look into this issue? @thomasmauerer Not a single response in months looks like this great project is more or less unmaintained, isn't it? 😢

**Comment by bcutter** [comment]
Summary:
1. File rename issue ("invalid date")
2. Status FAILED
3. Last backup attribute does not update

As simple as that. **Let's fix 1.** and everything will be fine again automatically ✅

**Comment by bcutter** [comment]
@thomasmauerer 👍🏼

**Comment by Tamsy** [comment]
> Following the closed issue #107 which does not seem to get any attention (closed).
> 
> Latest relevant information including an interesting finding:
> 
> * [Attribute "last_backup" does not update since 5.1.2 #107 (comment)](https://github.com/thomasmauerer/hassio-addons/issues/107#issuecomment-1505086586)
> * [Attribute "last_backup" does not update since 5.1.2 #107 (comment)](https://github.com/thomasmauerer/hassio-addons/issues/107#issuecomment-1509732100) <-- see "Suspicious finding 1" + "Suspicious finding 2" ⚠

Are you sure this is not caused by something with your particular installation?

The only difference I see is that you are doing partial backups while I have configured Samba Backup to do full backups every night. Thus doing partial backups might be the culprit.

Using Samba share on a QNAP-NAS for backups:

![samba_01](https://github.com/thomasmauerer/hassio-addons/assets/6210614/ba1aa025-30a4-4100-8dc6-a193bc2655c5)


"Last backup" attributes are showing correctly:
![samba_02](https://github.com/thomasmauerer/hassio-addons/assets/6210614/a7f8e2e1-9c3f-4f29-85b5-c4b4e74a7215)

Nothing in the logs and HA's Logbook says:

![samba_04](https://github.com/thomasmauerer/hassio-addons/assets/6210614/dec8cd88-00ff-48f6-8bf6-3c6bfcba7964)


Samba Backup logs show only:

![samba_03](https://github.com/thomasmauerer/hassio-addons/assets/6210614/ca4592cc-61b6-48b0-a3d9-ffb10b280cef)

**Comment by bcutter** [comment]
"I'm not affected" postings don't seem helpful in my opinion. All details on the core issue have been provided. It's up to a dev / the maintainer to make something out of this.

Partial/full backup shouldn't make any difference. Regarding the file rename bug (core of the issue) it's irrelevant (Partial|Full).

**Comment by bcutter** [comment]
Repeating the same information once again:

**SAMBA Backup addon log:**
![image](https://github.com/thomasmauerer/hassio-addons/assets/13799156/e1418363-c35e-43d8-b405-089ea3b594be)

_Plain text:_
```
[23-07-09 02:00:09] INFO: Backup running ...
[23-07-09 02:00:10] INFO: Creating backup "Partial Backup 2022.12.9 2023-07-09 02:00"
[23-07-09 02:36:56] INFO: Copying backup 9f09c58a (Samba_Backup_Partial_Backup_2022_12_9_2023_07_09_02_00.tar) to share
[23-07-09 02:38:03] INFO: Deleting dd832d82 (Partial Backup 2022.12.9 2023-07-08 02:00) local
date: invalid date 'umbenannt).tar A 3454935040 Sat Apr  8 06:49:24 2023'
[23-07-09 02:38:04] INFO: Deleting Samba_Backup_Partial_Backup_2022_12_9_2023_06_02_02_00.tar on share
[23-07-09 02:38:05] INFO: Deleting  on share
[23-07-09 02:38:05] WARNING: del <filename>
[23-07-09 02:38:16] INFO: Backup finished
```

**Corresponding SAMBA Backup sensor status:**
![image](https://github.com/thomasmauerer/hassio-addons/assets/13799156/7dcc524f-8e8f-483a-bf6c-70e3877469f3)

**Comment by Aggro600** [comment]
my backup failed a few times ([rename error](warning: XXX.tar does not exist)) and now may hard disk ist full. where is the location for the backup, before the Addon tries to rename it?

**Comment by bcutter** [comment]
I digged into this even more deeply.

1) Interesting: `keep_remote: "45"`, while log (set to debug) tells `..."backups_remote":"46"...`. How is this possible?
2) So I checked the SAMBA share once again. And found this, backup number 46 (the oldest one which should have been deleted already):
![grafik](https://github.com/thomasmauerer/hassio-addons/assets/13799156/7dcdf8bf-bdc7-4159-96ae-55ee7861972d)

I copied that one manually around 8th/9th of April. Remember SAMBA backup sensor: `"last_backup":"2023-04-09 02:29"`.

No coincidence, as this event matches the last successful backup date pretty closely.
...so I think it's basically a bad idea to manually copy SAMBA backups to the SAMBA share and rename it there. That's what the WARNING log entry seems to have been about. Somehow SAMBA backup can not handle such extra SAMBA backups on the SAMBA share/remote backup storage.

Long story short:

- I deleted that "extra" backup from the remote storage and triggered a SAMBA backup with minimal content (only `media` folder). It ran just fine (including SUCCEEDED state and an update of the `last_backup` attribute - FINALLY):
![grafik](https://github.com/thomasmauerer/hassio-addons/assets/13799156/7dd14d1c-d953-4005-b572-77d87edeca1e)
- It seems to be fixed based on that quick test.
- So I "were holding it wrong" - and the addon let me do so.
- I'd recommend to
   - ideally catch this in the code so the addon can handle this
   - at least put this in the docs, like "don't manually copy backups to the SAMBA backup remote storage and don't rename it there, the addon can not handle this and things will break!"
- **Summary: caused by myself, fixed by myself, only took me 3 months, thanks for nothing @thomasmauerer. Keep up the good work.**
