### ISSUE TITLE
Samba backup does not start if target device is offline and stops making backups until manually started

### ISSUE THREAD

**Issue by jbogers** [thomasmauerer/hassio-addons#148]
Samba backup does not start if target device is offline. This is problematic, for example if the target device is restarted at the same time as the Home Assistant device and Home Assistant starts up faster then the target device makes the SMB share available. This could, for example, happen if there is a power failure that affects both devices.

Relevant log (redacted):
```
WARNING: do_connect: Connection to REDACTED failed (Error NT_STATUS_HOST_UNREACHABLE)
FATAL: The provided host is unreachable. Please check your config and network.
```

This makes it possible for the backup process to be silently disabled. Instead, it would be desirable that samba backup would still (try to) run the backup tasks according to the backup schedule, especially if it was started after a system reboot/powerup.

**Comment by thomasmauerer** [comment]
That's how it's supposed to work. If you know what you are doing, you can use the `skip_precheck` option. With this the addon will not shut down.
--> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#option-skip_precheck

**Comment by Midbin** [comment]
Would it maybe be possible to have a persistent notification or some other notification, if the addon shuts down due to an error? As I wrote in #149 I found it to be surprising to have the addon silently failing and not running.

**Comment by thomasmauerer** [comment]
The addon provides a sensor --> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#home-assistant-sensor

If the checks during startup fail, the state will also switch to FAILED. You can use that in an automation for instance.
