### ISSUE TITLE
Discovered MQTT entities with a name that is equal to the device name

### ISSUE THREAD

**Issue by joselito11** [thomasmauerer/hassio-addons#154]
Got warning when upgraded Home Assistant to 2023.8
Discovered MQTT entities with a name that is equal to the device name

Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to null as a work-a-round to avoid a duplicate name. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

sensor.samba_backup

**Comment by thomasmauerer** [comment]
Must be a leftover on your setup. Mqtt was only used in this addon until v4.3.0. You can simply remove the sensor from your configuration, it is no longer needed.
