### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by kevorm** [thomasmauerer/hassio-addons#164]
Is there a way to give this a UID?  that would be great then i can hide it from the Overview dash instead of getting this

This entity ('sensor.samba_backup') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

when trying to make the Sensor not visible.

**Comment by thomasmauerer** [comment]
Unfortunately, that's not possible. See #102 for more details
