### ISSUE TITLE
"Backup Now" functionality? 

### ISSUE THREAD

**Issue by DReffects** [thomasmauerer/hassio-addons#170]
Hello there!

Great addon - just wanted to ask if there's a hidden "Backup now!" mechanic somewhere. I am playing around ALOT with HA and would love to have the ability to instantly create a backup when needed. 

Thanks :-)

**Comment by DReffects** [comment]
Ah sorry. nevermind my stupid question. After I was looking through the projects main github page i've posted, not reading up on the more detailed documentation linked from within the addon.

Here's a solution anyway for anyone else wondering:

Create a new automation "backupnow" that references the service hassio.addon_stdin and triggers:

> service: hassio.addon_stdin
> data:
>   addon: 15d21743_samba_backup
>   input: trigger



In your dashboard create a card with the following:

> show_name: true
> show_icon: true
> type: entity-button
> tap_action:
>   action: call-service
>   service: automation.trigger
>   service_data:
>     entity_id: automation.backupnow
> hold_action:
>   action: more-info
> entity: automation.sys_backupnow
> icon_height: 25px
> name: Create backup now
> icon: mdi:cloud-upload

**Comment by thomasmauerer** [comment]
Yes, using a manual trigger from a script is the way to go.
--> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#manual-triggers
