### ISSUE TITLE
Feature Request: Do not check for host on Start-Up

### ISSUE THREAD

**Issue by mike4001** [thomasmauerer/hassio-addons#171]
Hi,

I am doing my backup to my Synology NAS at 18:00 each day.

But my NAS is not always on but boots up at about 16:45 when I come home.

The problem is now if I reboot Home Assistant for instance at 09:00 the Addon tries to start but fails because it does not see the Host and stopps.

**Comment by thomasmauerer** [comment]
That's already supported with the skip_precheck option
--> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#option-skip_precheck

**Comment by mike4001** [comment]
Thank you very much
