### ISSUE TITLE
#Feature Request: Start manually

### ISSUE THREAD

**Issue by ifeelhorst** [thomasmauerer/hassio-addons#173]
Hi Thomas, thx for your great work.

It would be great sometimes to start a samba-backup on my own. 

Maybe it's possible to create a backup-entity (or something like that).

Would be nice (or maybe there is another way?).
Thx Horst

**Comment by thomasmauerer** [comment]
Please check the docs regarding manual triggers -> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#manual-triggers

You could for example create a button on your dashboard which calls the described script.
