### ISSUE TITLE
Backup doesn`t trigger

### ISSUE THREAD

**Issue by BurnyHa** [thomasmauerer/hassio-addons#180]
Hi there,
had Samba Backup already running on my Home Assistant. Now I renamed my backup targed, changed the path in the addon but now the backup doesn`t trigger anymore. According to the protocoll everything should be fine.
Any idea?

`-----------------------------------------------------------
 Add-on: Samba Backup
 Create backups and store them on a Samba share
-----------------------------------------------------------
 Add-on version: 5.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.4.3
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[24-06-26 21:37:52] INFO: ---------------------------------------------------
[24-06-26 21:37:52] INFO: Host/Share: 192.168.0.50/Backups
[24-06-26 21:37:52] INFO: Target directory: HomeAssistant
[24-06-26 21:37:52] INFO: Keep local/remote: 5/7
[24-06-26 21:37:52] INFO: Trigger time: 21:45
[24-06-26 21:37:52] INFO: Trigger days: Mon Tue Thu Fri Sat Sun
[24-06-26 21:37:52] INFO: ---------------------------------------------------
[24-06-26 21:37:53] INFO: Samba Backup started successfully`

**Comment by thomasmauerer** [comment]
> [24-06-26 21:37:52] INFO: Trigger days: Mon Tue Thu Fri Sat Sun

You did not specify "Wed", so it will not run on Wednesdays.

**Comment by BurnyHa** [comment]
Oh, yes.... Sorry for that.... Thank you!
