### ISSUE TITLE
SMB1?

### ISSUE THREAD

**Issue by mdm2207** [thomasmauerer/hassio-addons#20]
I have a USB drive connected to my router which I believe uses SMB1. It’s visible in my network but I’m getting the error ‘protocol negotiation failed’ with the Addon. Could this be the issue?
Thanks

**Comment by thomasmauerer** [comment]
Should be possible. I'll check that.

**Comment by thomasmauerer** [comment]
Implemented in v3.1. See option "compatibility_mode"

**Comment by mdm2207** [comment]
Awesome thank you. Working perfectly
