### ISSUE TITLE
sensor becomes unavailable overtime

### ISSUE THREAD

**Issue by defisit** [thomasmauerer/hassio-addons#23]
Hi,

When the add-on is started at boot or manually, the sensor is there and functioning fine. After a while though (don't know after how much time) the sensor becomes unavailable. I haven't monitored if backups are affected by this behaviour. The add-on does still run. I have to restart the add-on to get the sensor back. I'm running ha 115.3 but noticed the same behaviour in 114.x

<img width="577" alt="Schermafbeelding 2020-09-25 om 20 13 05" src="https://user-images.githubusercontent.com/61313374/94303622-67222d80-ff6e-11ea-9a2b-b53767ae1ed1.png">

**Comment by thomasmauerer** [comment]
This always happens if you restart Home Assistant. It's a known limitation, but you can fix that with an automation. Please check the docs --> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#home-assistant-sensor

**Comment by defisit** [comment]
thanks. I didn't know that about sensors which dont have an entity. The automation is an easy fix, thanks

**Comment by GitHubxtsnl** [comment]
the fix described here works like a charm. thank you.
https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#home-assistant-sensor
