### ISSUE TITLE
Enhancement Request: Compress the uploaded backup (gzip) 

### ISSUE THREAD

**Issue by kocsenc** [thomasmauerer/hassio-addons#27]
When uploading to samba share, it may be useful to compress the tarball with something like `gzip`. Since the intent is for backup purposes, being space efficient could be really cool.

**Comment by thomasmauerer** [comment]
The tar file is just a container in this case. All of the content is (with exception of a small json file) already compressed with gzip. So it will not save much disk space. I just tried it out - in my case the file size was reduced from 92MB to 89MB. The downside is that people need to manually unzip the backup file before Home Assistant is able to restore from it.

So I think the downside is actually bigger than the benefit in this case.

**Comment by nelgin** [comment]
I came here looking to file a request for compression on the remote stored file. The case that it's already compressed would be good in the documentation. I can't be the only person wondering why didn't he gzip the tar file.
