### ISSUE TITLE
FR: sync all snapshots, but only clean up automated snapshots

### ISSUE THREAD

**Issue by ktownsend-personal** [thomasmauerer/hassio-addons#28]
I have been looking at using this addon to replace my backup script. So far it looks like a good option, except I have one behavior that you don't have: preserve manual snapshots indefinitely. For example, if I manually make a snapshot it's usually before a core version update or after some major config changes. I like to keep those indefinitely. Perhaps you could add a config option for that behavior?

**Comment by thomasmauerer** [comment]
I actually had this behavior in one of the first versions, but I gave it up. Since the names are customizable, I do not know a reliable way to distinguish between snapshots that were made with this add-on and others.

**Comment by ktownsend-personal** [comment]
Maybe enable the feature with a config setting for a pattern mask of what to delete? That puts the responsibility on the user for what to match on, since they are also controlling the automatic file name.
