### ISSUE TITLE
Suppress PING to host

### ISSUE THREAD

**Issue by mathijsco** [thomasmauerer/hassio-addons#31]
Hi,

I'm trying out your addon to backup my snapshots to a Microsoft Azure Storage Account.
I lost my environment once and I don't want that again.
So this storage is very cheap, supports samba connections and therefore perfect.

However the firewall of those services blocks the ICMP protocol. The addon stops when it got no reply.
Is it possible to suppress the ping command? Perhaps some other way to test a connection?

Thank you!

Mathijs

**Comment by mathijsco** [comment]
I tried to remove the PING command my self and it still fails to connect. Now I get the error: "NT_STATUS_IO_TIMEOUT".
Perhaps this has something to do that Azure only supports SMB v3.

Do you know it that is supported in this addon or home assistant? Or somehow it is possible to add support for version 3.

**Comment by thomasmauerer** [comment]
Hi. Did you skip the entire pre-checks or only the ping? So in other words, do you get the NT_STATUS_IO_TIMEOUT during the pre-checks or during a real backup?

I have seen that status code before, mainly if the connection was unstable. But we can definitely rule out SMB protocol problems. All protocols are supported (even the old insecure ones if using the "compatibility_mode" flag). SMB3 is the default.

**Comment by thomasmauerer** [comment]
Implemented a config option to disable ICMP requests in v4.3.

Please create a separate issue for the NT_STATUS_IO_TIMEOUT and provide some (debug) logs if it is still an issue in your environment.
