### ISSUE TITLE
Workgroup/Domain Support

### ISSUE THREAD

**Issue by alexyao2015** [thomasmauerer/hassio-addons#33]
I use a domain authenticated share, so it requires the domain/workgroup field to be set to properly authenticate. 

For smbclient, it would be the -W flag to set the workgroup, used like so:
```
smbclient -W WORKGROUP
```

Hopefully, this would be an easy feature to implement. Here is a [link to the relevant code](https://github.com/thomasmauerer/hassio-addons/blob/0e49e81fc2a2e797a02cc5c7413b0cafccbc6c32/samba-backup/rootfs/scripts/config.sh#L54). Looking forward to a hopefully easy to implement feature!

**Comment by thomasmauerer** [comment]
Yes, that's not a big deal. I will add that in the next release.

**Comment by thomasmauerer** [comment]
Implemented in v4.3
