### ISSUE TITLE
Unable to connect to shared folder on Mac

### ISSUE THREAD

**Issue by danb5** [thomasmauerer/hassio-addons#34]
I run Hassio from a VirtualBox. Is there any known issues or special needs when connecting to the host computer (Mac) from a HomeAssistant (HASSIO) in a VirtualBox?  I keep getting the following message in the log "Failed to connect unknown error".

**Comment by thomasmauerer** [comment]
I guess the only requirement is that the virtual network is in general setup correctly, so that VMs are able to connect to the host network. Maybe you need an (additional) Host-only network adapter.
--> https://www.virtualbox.org/manual/ch06.html

**Comment by danb5** [comment]
Thanks but I just tested it.  It works if I use a shared folder from a PC but will not work with any of my shared folders on my Mac.  I have the folders shared with the SMB option selected.  Any ideas?

**Comment by thomasmauerer** [comment]
Maybe there is really something special with Mac shares. Unfortunately, I cannot debug this since I do not have any Apple device.

**Comment by nchiles** [comment]
I followed [this tutorial](https://www.chriswrites.com/how-to-share-files-folders-between-the-mac-and-pc/) to create a shared folder named **hassio-backups** on the Desktop of my mac.

Then configured the add-on:
host: _host mac IP address_
share: **hassio-backups**
target_dir: ''
username: new user created from tutorial
password: new user's password
keep_local: all
keep_remote: all
trigger_time: '00:00'
trigger_days:
  - Sun
exclude_addons: []
exclude_folders: []
backup_name: '{type} Snapshot (Samba Backup) {date}'

Seems to work fine, awesome add-on. Hope this helps.

**Comment by danb5** [comment]
I followed nchiles advice and sample configuration and it worked perfectly.  My issue was I was filling in the target directory path instead of leaving it blank as in nchiles example.  Thank you both for your help.  This is an awesome utility and should be included in the Official Add-ons!!

**Comment by thomasmauerer** [comment]
Awesome. Thanks for your responses.
