### ISSUE TITLE
Feature: Daily, Monthly, Yearly Backups

### ISSUE THREAD

**Issue by alexyao2015** [thomasmauerer/hassio-addons#36]
Hopefully a simple suggestion for having a daily, monthly, yearly backups. This would allow you to have backups that cover a longer period of time while also taking up less storage space.

Structure: 
3 folders named daily, monthly, and yearly under the base share directory
Every day/month/year do a backup to the respective folder
Only keep x backups in the daily/monthly/yearly folders with separate numbers for each

This would allow for a long term backup strategy while still being relatively simple to implement. 

Relevant link:
https://serverfault.com/questions/575163/how-to-keep-daily-backups-for-a-week-weekly-for-a-month-monthly-for-a-year-a

**Comment by thomasmauerer** [comment]
Thanks for your input, but I'm not going to implement this feature request. I try to keep the addon as simple as possible and this feature is out of the scope in my opinion.

The only goal of this addon is to get an off-device copy of a backup (plus some cleanup routines) without much further logic.
