### ISSUE TITLE
!secret working but said invalid

### ISSUE THREAD

**Issue by JohannCR** [thomasmauerer/hassio-addons#44]
Hi,
Awesome addon !
I managed to save the config using !secret and it worked well until reboot. Can't remember how I did it because the config editor now does not want to save with it nor start the addon again.

**Comment by thomasmauerer** [comment]
Not necessarily a problem with !secret. The configuration page does not show in which line the problem really is. So the easiest solution is probably to click on "reset to defaults" and configure it again. And make sure to use quotation marks when needed.
```
username: '!secret your_user'
password: '!secret your_pass'
```

**Comment by JohannCR** [comment]
A more helpful error message would've avoided my comment indeed ^^
Problem solved. Thanks for your answer !
