### ISSUE TITLE
WARNING: protocol negotiation failed

### ISSUE THREAD

**Issue by JJakaJonas** [thomasmauerer/hassio-addons#45]
Hello.

I'm trying to set this app up on my home assistent on my raspberry pi.

Here's my configuration:
host: 192.168.1.6
share: Backup
target_dir: ha-backups
username: myuser
password: mypassword
keep_local: '5'
keep_remote: '20'
trigger_time: '00:00'
trigger_days:
  - Mon
  - Tue
  - Wed
  - Thu
  - Fri
  - Sat
  - Sun
exclude_addons: []
exclude_folders: []
backup_name: '{type} Snapshot {version} {date}'

And everytime i start the app i get this in my log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:46:52] INFO: Host: 192.168.1.6
[14:46:52] INFO: Share: Backup
[14:46:52] INFO: Target Dir: ha-backups
[14:46:52] INFO: Keep local: 5
[14:46:52] INFO: Keep remote: 20
[14:46:52] INFO: Trigger time: 03:00
[14:46:52] INFO: Trigger days: Mon Tue Wed Thu Fri Sat Sun
[14:46:56] WARNING: protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
[14:46:56] FATAL: Cannot access share. Unknown reason.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Any idea what's the problem is?

**Comment by thomasmauerer** [comment]
Please check if smb3 is enabled in your NAS settings. Alternatively you could give it a try with the `compatibility_mode` option set to true.
--> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#option-compatibility_mode

**Comment by JJakaJonas** [comment]
That line gave this new error message:
[15:54:04] WARNING: Server does not support EXTENDED_SECURITY but 'client use spnego = yes' and 'client ntlmv2 auth = yes' is set session setup failed: NT_STATUS_ACCESS_DENIED [15:54:04] FATAL: Cannot access share. Access denied. Please check your share permissions.

Maybe is it a problem that it is a Apple airport time capsule?

**Comment by thomasmauerer** [comment]
Yes, that is most likely the problem. I do not know the Time Capsule, but from what I read it does only support smb1 and according to the new warning only an outdated authentication method, which smbclient (= this addon) refuses.

Maybe you find something in your settings regarding smb, but I actually think, you'll have to use a different NAS for this to work.

**Comment by JJakaJonas** [comment]
I'll just start looking for a better solution to replace the time capsule.

The only reason that i used that was do to that i hade one laying around.

**Comment by JJakaJonas** [comment]
It was the apple airport there was the problem.

I changed the NAS setup to a USB key in my router just to test it out.

And it works as long as I use the compatibility mode.
So now it's just time to find a more secure solution.
