### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by AgentP38** [thomasmauerer/hassio-addons#47]
Hi I just have a question. 

After bacup restauration it was a problem with Backup of Mariadb files. So is there a possibility to stop the maria service before starting the backup?

**Comment by thomasmauerer** [comment]
I don't really understand the question and how it is related to Samba Backup. Creating snapshots is handled by the supervisor. It is exactly the same if you create a snapshot manually via the UI.
You can always stop the MariaDB addon if you want to, but that's probably not the solution to your problem.

**Comment by robloh** [comment]
This is a "known" issue with Home Assistant. It does not really have a proper backup infrastructure which means that backups can be created will the sqlite or MariaDB databases are being updated. This is a Home Assistant problem that can happen with manual backups as well.

For more info see this issue: https://github.com/home-assistant/addons/issues/1353

I can't think of a way for this addon to work around that really.

**Comment by thomasmauerer** [comment]
Thanks for the clarification. Now it's much clearer.
But I'm not sure if this addon is really a good location for such workarounds. I would say we have to wait for an official solution from Home Assistant. 

Alternatively you could create an automation yourself which triggers shortly before Samba Backup and stops the MariaDB addon until there is an official solution. Something like that:
```
service: hassio.addon_stop
data:
  addon: core_mariadb
```

**Comment by AgentP38** [comment]
Thx alot... I will try it

**Comment by poudenes** [comment]
I asked this question also on Forum HA this morning. Google Drive Backup have the option to stop addon before backup. When backup is done it will start the addon again. This prevent problems with MariaDB after a restore.

**Comment by thomasmauerer** [comment]
This should not be needed anymore, as MariaDB now locks the tables during backups. See changelog for MariaDB:
```
2.4.0
- Add lock capabilities during snapshot
```

I have not tested it myself.

**Comment by poudenes** [comment]
Thats true, read it also but lost the info. I will create a dev HA on a RPi and restore the image and see what happen.
