### ISSUE TITLE
How to create a partial snapshot without Homeassistant core?

### ISSUE THREAD

**Issue by jodur** [thomasmauerer/hassio-addons#48]
Thnx for this wunderfull add-on. 
I was exploring this addon to use it to backup specific addons. 
To bad it supports only exclude list, but this isn't the biggest issue i have.

I didn't find a way to create a partial snapshot **without** "home-assistant core" 
I didn't find also any documentation if this is even possible with the command-line  `ha snapshot`  command?
Any clues about this?

**Comment by thomasmauerer** [comment]
You just need to exclude the "homeassistant" folder:

`exclude_folders: ['homeassistant']`
