### ISSUE TITLE
Backup Naming

### ISSUE THREAD

**Issue by brucek1642** [thomasmauerer/hassio-addons#5]
I like the changes you made to allow including the version. I would suggest one change to use "version" instead of "latest_version"

theversion=$(ha core info --raw-json | jq -r .data.version_latest)

I noticed when I did a manual backup "before" updating to 0.111.0. The backup of 0.110.6 was labelled as 0.111.0

Thanks for your efforts

**Comment by thomasmauerer** [comment]
Fixed in v2.1
