### ISSUE TITLE
Can't save the configuration

### ISSUE THREAD

**Issue by matlar83** [thomasmauerer/hassio-addons#52]
After a fresh install of the add-on, I can't save the configuration.

As soon as I press the "SAVE" button, my configuration is replaced with the default configuration.
Even if my configuration is composed only by the host and share keys, the configuration is not saved but replaced every time the save button is pressed.

Running core-2021.4.3 with supervisor-2021.03.9 on Home Assistant OS 5.13 (Raspberry PI 4).

Thank you

**Comment by thomasmauerer** [comment]
Did you try it with single quotation marks? I'm running the same setup, but I cannot reproduce it.

**Comment by matlar83** [comment]
I just got it!

This happens when the configuration is composed just by host and share keys.
Even if I just need these two keys, I have to keep all the other ones with
default values.
In this way, everything works as expected!

Thanks
Matteo

Il giorno lun 12 apr 2021 alle ore 10:28 Thomas Mauerer <
***@***.***> ha scritto:

**Comment by thomasmauerer** [comment]
Ah ok cool. Yes, you can only omit the optional parameters, e.g. log_level. The rest must be present.
