### ISSUE TITLE
Option to reset the failed backup counter

### ISSUE THREAD

**Issue by collse** [thomasmauerer/hassio-addons#56]
first of all thanks for this as it works just fine.

but unless I have missed anything, there is no option to reset the failed backup counters?

**Comment by thomasmauerer** [comment]
Only resetting the failed backup counter is too specific from my point of view, but a function to reset the entire sensor would be a good idea.

In the meantime if you need to, you can simply delete (or adjust) the hidden file ".samba_backup.sensor" in the backup folder on your HA device.

**Comment by thomasmauerer** [comment]
Implemented in v5.0.0.
