### ISSUE TITLE
Samba Backup: Resetting the total count counter

### ISSUE THREAD

**Issue by DivanX10** [thomasmauerer/hassio-addons#58]
I have a question regarding sensors for calculating the number of backups. I don't understand how the total backup succeeded sensor works. Why do I need this total backup succeeded sensor? Why count the total number of successful backups? As I understood that this sensor counts the total number of successful copies and regardless of whether the home assistant is rebooted or not, the accounting is conducted similarly to the odometer on the car. Is it possible to redo the logic of total backup succeeded? For example, take into account the total number of successful backups that are stored both locally and on a network folder ( display the real number of backups ) or reset the total backups succeeded account after restarting the home assistant.

```
The sensor includes the following attributes:

backups local: The current number of snapshots available on the device
backups remote: The current number of snapshots available on the Samba share
total backups succeeded: The total number of successful backups made with this add-on
total backups failed: The total number of failed backups
last backup: The date of the last successful backup
```

**Comment by thomasmauerer** [comment]
You can view it as statistics for this add-on. It's exactly the same principle as the "total backups failed". Since this is the _total_ number, it does not make sense to reset it after reboot.

> For example, take into account the total number of successful backups that are stored both locally and on a network folder

This information is given by the "backups local" and "backups remote" attributes.

**Comment by DivanX10** [comment]
I do not understand. Why do I need to keep track of the total number of copies made? What's the point of that?
![image](https://user-images.githubusercontent.com/64090632/124488831-fb9ca480-ddb8-11eb-8ff9-4815eba036c8.png)

I understand the meaning of taking into account the number of local and remote copies, this displays the real number of copies created and stored on disks, which I did. I brought out the sensors, but the general accounting of the number of copies baffles me. It's just like an odometer in a car. In the car, the odometer is put to account for the total number of mileage and its task is to provide data on the distance traveled for a certain time and the total mileage indicator, and this is taken into account when buying a car.

Sensors for the number of local and remote copies
![image](https://user-images.githubusercontent.com/64090632/124488676-c7c17f00-ddb8-11eb-9c8b-6d04304063d0.png)

**Comment by thomasmauerer** [comment]
> Why do I need to keep track of the total number of copies made?

You don't have to if it's no usecase to you.

It's just a counter. Some people find it interesting to know how many runs of this add-on have succeeded or failed.
