### ISSUE TITLE
Addon terminates if host server is unreachable.

### ISSUE THREAD

**Issue by DeeBeeKay** [thomasmauerer/hassio-addons#62]
Hi,

  First let me say, thank you for this useful add-on. It is most excellent.

  However, I have discovered a problem with it. I have this add-on configured to take daily backups at 03:00. I noticed today that they have not been done for the last 5 days, so I went to look at the logs of the add-on.

  It looks like this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:44:55] INFO: Host: 192.168.1.125
[21:44:56] INFO: Share: habackup
[21:44:56] INFO: Target Dir: 
[21:44:56] INFO: Keep local: 5
[21:44:56] INFO: Keep remote: 5
[21:44:56] INFO: Trigger time: 03:00
[21:44:56] INFO: Trigger days: Mon Tue Wed Thu Fri Sat Sun
[21:45:01] WARNING: do_connect: Connection to 192.168.1.125 failed (Error NT_STATUS_HOST_UNREACHABLE)
[21:45:01] FATAL: The provided host is unreachable. Please check your config and network.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

What happened 5 days ago is that we had a power failure, and were running the house on a battery backup inverter. If the battery drops below 60%, Home Assistant begins shutting down non-essential appliances like the washer/dryer, the TV, and the backup server. So the server was shut down when this backup ran.

However, we were off for so long that the whole house eventually died, and it could be that this occurred when Home Assistant was restarting, because the server was also still off at that point. Now that I think about it, this seems more likely: the host was offline when the add-on started.

So it seems like, if the addon can't find the configured host, it doesn't recover, and the process dies, which means the next backup never runs. I guess if that's a startup error, that's kind of normal behaviour. I just would prefer if it doesn't die if the host doesn't respond. I'd prefer for it to miss one backup than to completely die because I have no way of noticing this has happened.

**Comment by thomasmauerer** [comment]
Hi. Actually the addon has already your desired behavior: if the connection to the host is broken, the backup will fail, but the addon will continue running and start the next backup according to the schedule. It looks like the addon was shut down for a different reason here.

The thing is that the addon cannot start when the host is not reachable. That is due to the pre-checks which I introduced because I saw quite many users having troubles with the configuration. You can take a look at the `skip_precheck` option to make the addon start (again) even if the host is not reachable during startup.
