### ISSUE TITLE
Home Assistant Supervisor API Changes - Snapshots renamed to Backups

### ISSUE THREAD

**Issue by sqldiablo** [thomasmauerer/hassio-addons#63]
Hi there,

It looks like they've deprecated the snapshot terminology in the Home Assistant Supervisor and moved over to calling them backups. This means that the snapshot API calls used by this addon are now deprecated and need to be switched over to the new ones that use backup instead of snapshot.

Details here: https://developers.home-assistant.io/blog/2021/08/24/supervisor_update/#snapshot---backup

**Comment by thomasmauerer** [comment]
Hi. The necessary changes are already implemented in the dev branch. I'm going to release an update soon when I have time for final testing.

**Comment by odjhl88** [comment]
Excellent! I was wondering about this too. Thank you for your continued development of this add-on.

**Comment by pvmil** [comment]
Thanks for updating thomas, excellent plugin

**Comment by thomasmauerer** [comment]
Implemented in v5.0.0.
