### ISSUE TITLE
Exclude_addons doesn't work

### ISSUE THREAD

**Issue by KixMan28** [thomasmauerer/hassio-addons#69]
Hi! Thank you for this integration. I have added couple of add-ons to the "exclude_addons" list, but when the backup is created the excluded add-ons are still saved in the file. What am I doing wrong?
![2021-11-01 11_12_55-Search](https://user-images.githubusercontent.com/33165356/139656513-228bdd98-7c83-4b7b-ba11-68324fb19fc0.jpg)
![2021-11-01 11_16_10-Action center](https://user-images.githubusercontent.com/33165356/139656610-91056dc9-7e4b-451d-a8a7-7fd835d976f7.jpg)

**Comment by thomasmauerer** [comment]
Hi. The names are wrong. All the hyphens should be underscores, e.g. `core_mariadb`

**Comment by KixMan28** [comment]
Thank you. I will update my setup and let you know the result.

**Comment by KixMan28** [comment]
@thomasmauerer Thank you for your suggestion, it works now as expected.
