### ISSUE TITLE
Service restart counters not working:

### ISSUE THREAD

**Issue by alnavasa** [thomasmauerer/hassio-addons#71]
service to reset counters not working.

`service: hassio.addon_stdin

data:

  addon: 15d21743_samba_backup

  input: reset-counter`

<img width="1255" alt="Captura de pantalla 2021-11-26 a las 0 40 35" src="https://user-images.githubusercontent.com/458370/143508080-8ef87b3a-669b-43be-8721-6980aa5632ff.png">

**Comment by alnavasa** [comment]
use it, counters still there

**Comment by lullerboi** [comment]
The counters are also wrong if you manually delete backups. You can set the state to the correct values manually but restarting HA will restore the wrong ones, once again.
The plugin should be able to count the actual numbers.

**Comment by thomasmauerer** [comment]
Issue fixed in v5.2.0.

Apart from that, the current number of stored backups is now also checked at startup.
