### ISSUE TITLE
Error when adding repository to HACS: Repostitory structure for master is not compliant

### ISSUE THREAD

**Issue by SteffanH** [thomasmauerer/hassio-addons#72]
When adding the repository to HACS, I get the following error message: Repostitory structure for master is not compliant
![image](https://user-images.githubusercontent.com/866619/144177086-b6082639-b869-4d44-b7d8-999e7e04d1ca.png)
<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(225, 225, 225); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(28, 28, 28); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Community Store</h3></div>

GitHub API | ok
-- | --
Github API Calls Remaining | 4979
Installed Version | 1.18.0
Stage | running
Available Repositories | 910
Installed Repositories | 2

</body>
</html>

**Comment by thomasmauerer** [comment]
You have to add the repository on the supervisor page (Add-on Store). This has nothing to do with HACS.

**Comment by SteffanH** [comment]
Thank you for your response and pardon my ignorance 🤦‍♂️
