### ISSUE TITLE
NT_STATUS_INVALID_NETWORK_RESPONSE

### ISSUE THREAD

**Issue by gumbyCAD** [thomasmauerer/hassio-addons#73]
When configuring I get the following error:

[22-01-01 21:07:32] WARNING: protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
[22-01-01 21:07:32] FATAL: Cannot access share. Unknown reason.

How do I fix this?

host: XXX.XXX.X.XXX
share: config/downloads
target_dir: /Home_Assistant_Samba_Backup
username: ???????????
password: ?????????????
keep_local: 5
keep_remote: 20
trigger_time: '04:00'
trigger_days:
  - Mon
  - Tue
  - Wed
  - Thu
  - Fri
  - Sat
  - Sun
exclude_addons: []
exclude_folders: []
workgroup: WORKGROUP
backup_name: '{date} Backup {type}'

**Comment by thomasmauerer** [comment]
`config/downloads` is not a valid name for a share. You need to enter the correct name of the share. You could use a Windows PC to find out the name. Just type in `\\` followed by the host address in the file explorer.

The target directory is a folder inside the share. Remove the leading `/`.

**Comment by thomasmauerer** [comment]
Issue closed due to lack of feedback.
