### ISSUE TITLE
Sensor not working since HA core 2022.2

### ISSUE THREAD

**Issue by therealhalifax** [thomasmauerer/hassio-addons#78]
Since the update to HA core 2022.2 the sensor is not working anymore. If I restart the addon it's working for some minutes but then it stops again.

**Comment by SawKyrom** [comment]
Same here with core-2021.12.10.  Sensor restore automation not working and manual service call to restore-sensor ineffective as well.

**Comment by thomasmauerer** [comment]
What do you mean with "stops working"? The sensor is not constantly updating, only after a backup. Please also see the info from @SawKyrom and check if the addon is really running.

**Comment by thomasmauerer** [comment]
The sensor is unavailable when you restart Home Assistant. This is described in the docs as a known limitation. Sounds like you're not using the automation to restore the sensor.
--> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#home-assistant-sensor

**Comment by therealhalifax** [comment]
Got it!

Many thanks 🤗

**Comment by thomasmauerer** [comment]
Cool. So I can close this issue.
