### ISSUE TITLE
share name containing the '&' symbol

### ISSUE THREAD

**Issue by Galvinized83** [thomasmauerer/hassio-addons#8]
Connection seems to fail when a share name contains the '&' symbol. 

output:
`[21:00:56] WARNING: scripts/helper.sh: line 42: Assistant: command not found
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
[21:00:56] FATAL: Cannot access share. Please check your config.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by thomasmauerer** [comment]
The & symbol has a special meaning in bash and it's not escaped correctly here.

**Comment by thomasmauerer** [comment]
Fixed in v2.4
