### ISSUE TITLE
I write a blueprint for restore Samba Backup sensor on startup

### ISSUE THREAD

**Issue by findix** [thomasmauerer/hassio-addons#82]
[![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgist.github.com%2Ffindix%2Fbaead17c646c04cd4975282392fecf62)

https://gist.github.com/findix/baead17c646c04cd4975282392fecf62

May be useful for someone XD

**Comment by thomasmauerer** [comment]
Sorry for late response and thanks a lot for the blueprint. That's really useful. I integrated it into this repository and linked it in the docs.
