### ISSUE TITLE
Sensor disappearing 

### ISSUE THREAD

**Issue by BNWEIN** [thomasmauerer/hassio-addons#84]
The Samba backup sensor seems to just disappear randomly. 

Restarting the add-on brings it back but then it goes again?

**Comment by N1c093** [comment]
This is a "normal" behavior see documentation: https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#home-assistant-sensor

You will also find a workaround for this problem over there.

**Comment by thomasmauerer** [comment]
Thanks @N1c093 for mentioning the docs.
