### ISSUE TITLE
{date} option in filename causes backup to fail with macOS SMB shares

### ISSUE THREAD

**Issue by nimartin28** [thomasmauerer/hassio-addons#87]
Great add on, congrats!

One note: Using the {date} option in the filename causes it to create a backup filename with a colon. This, in turn, causes backup to fail on a macOS Samba share because macOS does not allow colons in filenames.

Solution: For me at least, having a {date} that only appended the date and a new {time} option for time or date/time would solve the problem since I don't do more than one backup a day. More work would be to allow the user to add a format string to the {date}.

Verification: I verified by turning on debug logging and running the add-on with and without the {date} option in the filename. It runs fine if {time} is not used. If {time} is included in the filename, it returns an error that the file doesn't exist when trying to back up.

Thanks.

**Comment by thomasmauerer** [comment]
I cannot reproduce this issue. Colons are (as all forbidden characters) replaced with an underscore. On my setup a filename with a date looks like this: `Samba_Backup_2022_07_01_17_28.tar`
