### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by Coolie1101** [thomasmauerer/hassio-addons#88]
Any idea why the file name is different when accessed directly via the backup folder, compared to the UI?, it makes it difficult if trying to restore a full system config on a new install if the system crashed.

**Backups UI**
![image](https://user-images.githubusercontent.com/28989417/173874058-c7917f88-75f2-40a1-b0ec-9e1c1ed35add.png)
>
**Backups folder**
![image](https://user-images.githubusercontent.com/28989417/173874152-e40f0c0c-bcb7-4653-a427-1dc2fbb66c67.png)

**Comment by Coolie1101** [comment]
> When copying the files to the share, Samba Backup renames the files to the name that is shown in the UI.

Are you saying the above is what should happen?, as this is not the case.

**Comment by Coolie1101** [comment]
> When copying the files to the share, Samba Backup renames the files to the name that is shown in the UI.

Is it possible to add Full/Partial to the name when copied to the share?
![Screenshot_20220930-052716_(1)](https://user-images.githubusercontent.com/28989417/193240124-2384b3e5-bd1b-4980-be31-697bfbd18bfc.png)

**Comment by thomasmauerer** [comment]
Yes, just include `{type}` in the backup_name option
--> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#option-backup_name

**Comment by Coolie1101** [comment]
> Yes, just include `{type}` in the backup_name option

Awesome, thanks for the quick response.

**Comment by Coolie1101** [comment]
After adding {type}, will the output be as below?

Samba_Backup_Full_2022_09_30_02_55.tar

**Comment by Coolie1101** [comment]
Also, would it be possible to add a file size sensor for the backup file?, or is the another way within HA?
