### ISSUE TITLE
Update to 5.1.0 seems to have broken my sensor.samba_backup?

### ISSUE THREAD

**Issue by dvisser** [thomasmauerer/hassio-addons#92]
I updated to 5.1.0 and it appears to have broken my sensor.samba_backup?

I was running the startup automation to restore the sensor prior to updating to 5.1.0 also. I have tried manually triggering the restore sensor automation also with no luck.

**Comment by twinkie0101** [comment]
I had similar issue and backup didn't run this morning for me.  Checked addon and said log_level entry was missing from configuration.  Reinstalled addon, testing now, will report back results shortly, just tried to trigger a backup.

**Comment by dvisser** [comment]
Confirmed. 

Seems the update doesnt select a default log level. Once a log level is selected and the addon restarted, the issue is resolved.

Maybe add log level = error to the default config? 

Thankyou.

**Comment by thomasmauerer** [comment]
Issue is fixed in v5.1.1. The log level is now optional again.
