### ISSUE TITLE
how is the proc to do the restore after de backup?

### ISSUE THREAD

**Issue by heuvep** [thomasmauerer/hassio-addons#94]
Hello,

I can not read how to do the restore if needed after the backup samba add-on works

grt

Pierre

**Comment by JensJott** [comment]
It should be dead simple.

Normal procedure:

- Upload the created file using the "..." menu under _Settings -> System -> Backups_
- Restore as usual

Desaster Recovery:

- Install HA in exact the same version your backup was created
- Follow "Normal procedure"

**Comment by thomasmauerer** [comment]
Thanks for the answer @JensJott

One little comment to the "Desaster Recovery": You can directly restore from a backup on the onboarding page. No need to reinstall Home Assistant in the same version.

![onboarding](https://user-images.githubusercontent.com/12152547/178049710-f490824a-2407-4d6b-a114-065192e2054a.png)
