### ISSUE TITLE
Just commenting: Automation trigger

### ISSUE THREAD

**Issue by emefff** [thomasmauerer/hassio-addons#99]
Hello,
in HA 2022.7.3 triggering a backup with an automation also works without setting 'Trigger time' to 'manual'. What I mean is: in 'Trigger time' there can be a time entry. Great add-on by the way :-),
cheers,
Mario

**Comment by thomasmauerer** [comment]
Hi. That's how it's supposed to work. I changed the text in the docs, hopefully it's clearer now
--> https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#option-trigger_time

**Comment by emefff** [comment]
:-) I was too finicky... thank you, 
Mario.
